### PR TITLE
Real Men Learn Golang Together ;) - Improvements Patch

### PR DESCRIPTION
**Pull request by zikaura**

### CODE REVIEW

**Comment by noornee** [comment]
lmaoo :D
nicee!

**Comment by zikaura** [comment]
Still got discord? Drop your username

**Comment by noornee** [comment]
yeah sure!
noornee#8872

**Comment by noornee** [comment]
btw thanks for following me back UwU

**Comment by zikaura** [comment]
> yeah sure! noornee#8872

I just sent you an fr, finally

**Pull request merged**
